### ISSUE TITLE
PIN is requested every time 

### ISSUE THREAD

**Issue by ngortheone** [str4d/age-plugin-yubikey#115]
age-plugin-yubikey: latest main build with latest yubikey crate patch (see https://github.com/str4d/age-plugin-yubikey/issues/114)
I have YubiKey-4-Nano
`OS: FreeBSD-14`
`pcsc-lite version 1.9.9.`

```
#       Serial: 0, Slot: 1
#         Name: age identity xxxxx
#      Created: Sat, 28 Jan 2023 08:22:29 +0000
#   PIN policy: Once   (A PIN is required once per session, if set)
# Touch policy: Always (A physical touch is required for every decryption)
```

every time I decrypt a file a PIN is requested
```
cat ./secret.age| age -i ./age-yubikey-identity-xxxx.txt --decrypt
```

- pin policy is set to once
- yubikey was not {un|re}plugged
- no other agents are running
- pcscd service was not restarted

**Comment by str4d** [comment]
I think this may be fixed by #116. Can you test that branch?

**Comment by str4d** [comment]
Also note that this behaviour is expected for version 0.3 and earlier; the PIN caching changes referenced in the README will be in the upcoming version 0.4 (as they require a new release of the `yubikey` crate).

**Comment by ngortheone** [comment]
Will test and report shortly

**Comment by ngortheone** [comment]
Unfortunately the PIN is still requested every time :(

**Comment by str4d** [comment]
Hmm. I wouldn't be surprised if this issue is something specific to YubiKey 4. But I'm not sure how to debug this further...

**Comment by ngortheone** [comment]
Would it be helpful if I provide pcscd logs or some other debug info?

**Comment by str4d** [comment]
Yeah, running with `RUST_LOG=trace` and then reproducing the issue would be helpful. I've just released v0.3.3 and merged that back in, as well as merging #116, so it would be best to test the current `main` branch.

**Comment by supermarin** [comment]
Same problem on a 5C Nano & 0.3.2. Will test today with 0.3.3 and report back if it's still happening.

**Comment by supermarin** [comment]
Still an issue on 0.3.3, nixos, linux 6.1.9, YubiKey 5C Nano

**Comment by str4d** [comment]
@supermarin It is expected behaviour on 0.3.3 and earlier, because the PIN cache preservation logic is being targeted for 0.4.0 (as it requires upgrades to the `yubikey` crate).

If you want to test, could you please try building from the `main` branch?

**Comment by supermarin** [comment]
@str4d gotcha, my bad! Tried quickly building `main` but it failed:
```
', /build/age-plugin-yubikey-70c109aa1db99b12613768b00a0b830838859aa8-vendor.tar.gz/openssl-sys/build/find_normal.rs:191:5
```
Don't have the whole backtrace or time ATM, might be able to resolve it tonight or tomorrow.

**Comment by str4d** [comment]
I just realised that preserving the internal PIN cache may be impossible for YubiKey 4. This is because YubiKey 5 was the first to implement a PIV applet command to get the serial, so on YubiKey 4 we instead need to [switch to the OTP applet to retrieve the serial](https://github.com/iqlusioninc/yubikey.rs/blob/1e02f135f027716d4f155152b6a68e002b948097/src/transaction.rs#L106-L115). We can't avoid this because we need the serial for a bunch of things (most notably, when decrypting something we look up the correct YubiKey to use by serial).

According to [NIST SP 800-73-4, Part 2, Section 3.1.1](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf):

> If the currently selected application is the PIV Card Application when the SELECT command is given and the AID in the data field of the SELECT command is either the AID of the PIV Card Application or the right-truncated version thereof, then the PIV Card Application shall continue to be the currently selected card application and the setting of all security status indicators in the PIV Card Application shall be unchanged.
>
> If the currently selected application is the PIV Card Application when the SELECT command is given and the AID in the data field of the SELECT command is not the PIV Card Application (or the right-truncated version thereof), but a valid AID supported by the ICC, then the PIV Card Application shall be deselected and all the PIV Card Application security status indicators in the PIV Card Application shall be set to FALSE.
>
> If the currently selected application is the PIV Card Application when the SELECT command is given and the AID in the data field of the SELECT command is an invalid AID not supported by the ICC, then the PIV Card Application shall remain the currently selected application and all PIV Card Application security status indicators shall remain unchanged.

This means that the act of selecting the OTP applet is required to clear the PIN cache of the PIV applet.

From a bit of searching, it appears that some applications resort to caching the PIN themselves once the user enters it (effectively replicating the PIV applet's internal PIN cache). But `age-plugin-yubikey` is inherently an ephemeral app, so there'd be no benefit in implementing this.

So I think I will just need to document in the README that PIN cache preservation does not work on YubiKey 4.

**Comment by ngortheone** [comment]
@str4d I have a philosophical question :)
How can `age-plugin-yubikey` persist the PIN between invocations, if `age-plugin-yubikey` itself does not persist? :thinking: 

I.e. `age-plugin-yubikey` is not a daemon, not a long running process, every time I run `age` to decrypt something a new `age-plugin-yubikey` process is spawned. Where PIN is cached? on disk (is it secure to store it on disk vs in-memory)? 

Could this problem be avoided if `age-plugin-yubikey` was a long running process?

**Comment by str4d** [comment]
> @str4d I have a philosophical question :) How can `age-plugin-yubikey` persist the PIN between invocations, if `age-plugin-yubikey` itself does not persist? 🤔

Prior to (the upcoming) 0.4.0, it did not! I generally didn't think it possible.

> I.e. `age-plugin-yubikey` is not a daemon, not a long running process, every time I run `age` to decrypt something a new `age-plugin-yubikey` process is spawned. Where PIN is cached? on disk (is it secure to store it on disk vs in-memory)?

Inside the YubiKey itself 🙂

The YubiKey has its own internal PIN cache, which is a necessary aspect of offering a PIN policy of "Once". This is the "PIV Card Application security status indicators" referenced in the NIST specification to be more precise, I believe it is caching the fact that a PIN has been entered at some point since the YubiKey's PIV applet was started; the PIN itself likely isn't cached anywhere.

What we are relying on is the fact that, as long as you don't unplug the YubiKey or select a different applet, the YubiKey's internal cache won't be cleared.
- This works across applications: if you are using your YubiKey with `yubikey-agent` for SSH authentication and have entered your PIN, and then you try to decrypt a file with `rage` and `age-plugin-yubikey` using an age identity with a policy of "Once", the cached PIN entry allows decryption without re-entering a PIN.
- This doesn't work across applets: if you are using your YubiKey with both `age-plugin-yubikey` and for FIDO2 authentication, each time you use the FIDO2 function for WebAuthn, the PIV applet's internal cache gets cleared. Same thing if you are trying to use `age-plugin-yubikey` at the same time as an OpenPGP app (like `gpg` via `scdaemon`).

> Could this problem be avoided if `age-plugin-yubikey` was a long running process?

A long running process for handling YubiKey access would by definition be an agent; this is what I mention in the README. An agent could _mostly_ avoid this problem, but only by caching the PIN in memory (so it could not reuse the PIN entry from a different PIV app, but once the user had entered the PIN into the agent, it could then re-enter the PIN any time the user wants to use a key with a PIN policy of "Once"). I'll note that this would _also_ enable the agent to treat keys with a PIN policy of "Always" as if they had a PIN policy of "Once", but that would be a dereliction of duty on the part of the agent.

`age-plugin-yubikey` itself cannot be long-lived (it is invoked by the age client, which itself is ephemeral). Instead you'd have an age agent plugin that, when invoked, communicated with the long-running process. Most likely it would be made as an extension of `yubikey-agent`. But my goal with 0.4.0 is to try and make using `age-plugin-yubikey` on its own as nice as possible, and it seems we are most of the way there.

**Comment by supermarin** [comment]
@str4d confirming it works as intended on bf437663af22ba6492fc738d3e1bdf6d6cc2a00a. w00t!

**Comment by ngortheone** [comment]
I have yubikey 5 lying around, I will test if PIN caching works with #116

**Comment by ngortheone** [comment]
PIN caching for Yubikey 5C on #116 indeed works, so @str4d is right, the problem is with 4 series

**Comment by str4d** [comment]
Closing this issue as complete. PIN caching works about as reliably as we can make it on YubiKey 5, and the fact that it doesn't work with YubiKey 4 is documented in the README.
